// Authored deterministic content; snippets are displayed as text, never executed.
export const builderChallenges = [
  {id:'build-greeting',difficulty:'beginner',prompt:'Give Pip a greeting. Create the message before saying it.',blocks:['let message = "Hello!";','console.log(message);'],correctOrder:[0,1],explanation:'Create the variable first, then read it to display the greeting.'},
  {id:'build-score',difficulty:'beginner',prompt:'Start with 0 points, earn 10, then show the score.',blocks:['let score = 0;','score = score + 10;','console.log(score);'],correctOrder:[0,1,2],explanation:'The score must exist before it can be updated. Display it after adding the points.'},
  {id:'build-array',difficulty:'beginner',prompt:'Make a kit, add a map, then display its first item.',blocks:['const kit = [];','kit.push("map");','console.log(kit[0]);'],correctOrder:[0,1,2],explanation:'Create the array, add an item, then read index 0: the first item.'},
  {id:'build-if',difficulty:'intermediate',prompt:'Check whether Pip has a key before opening the gate.',blocks:['const hasKey = true;','if (hasKey) {','  console.log("Gate open!");','}'],correctOrder:[0,1,2,3],explanation:'Set the condition, open the if block, run its action, then close the block.'},
  {id:'build-loop',difficulty:'intermediate',prompt:'Count the three checkpoints: 1, 2, 3.',blocks:['for (let step = 1; step <= 3; step++) {','  console.log(step);','}'],correctOrder:[0,1,2],explanation:'The loop starts at 1 and increases after each pass, stopping after 3.'},
  {id:'build-function',difficulty:'intermediate',prompt:'Define a greeting arrow function, then call it.',blocks:['const greet = () => {','  console.log("Hi, explorer!");','};','greet();'],correctOrder:[0,1,2,3],explanation:'This function is stored in a const variable, so define it before calling it.'},
  {id:'build-total',difficulty:'advanced',prompt:'Add every gem in the bag to a total, then display it.',blocks:['const gems = [2, 3, 4]; let total = 0;','for (const gem of gems) {','  total += gem;','}','console.log(total);'],correctOrder:[0,1,2,3,4],explanation:'Set up the collection and total, add each gem inside the loop, then display 9 after the loop.'},
  {id:'build-return',difficulty:'advanced',prompt:'Create a doubling function, use it on 4, then show 8.',blocks:['const double = (number) => {','  return number * 2;','};','const result = double(4);','console.log(result);'],correctOrder:[0,1,2,3,4],explanation:'Define the function with its return value, call it with 4, then display the returned 8.'},
  {id:'build-filter',difficulty:'advanced',prompt:'Display each score of 10 or more.',blocks:['const scores = [5, 10, 15];','for (const score of scores) {','  if (score >= 10) {','    console.log(score);','  }','}'],correctOrder:[0,1,2,3,4,5],explanation:'The condition sits inside the loop. Close the if block before closing the loop.'}
];
const debugRows = [
 ['beginner','debug-name','A message went missing.','let message = "Hi!";\nconsole.log(mesage);','The variable name is misspelled','console.log cannot show text','let cannot store a string','Use message consistently; mesage refers to a different, undeclared name.'],
 ['beginner','debug-string','Pip’s greeting will not load.','const greeting = "Hello!;','The string needs a closing quote','const is not a keyword','Exclamation marks are forbidden','A string’s opening quote needs a matching closing quote.'],
 ['beginner','debug-first','The first gem is wrong.','const gems = ["ruby", "opal"];\nconsole.log(gems[1]); // wanted ruby','Use index 0 for ruby','Arrays cannot contain strings','Use gems[2] for ruby','Array indices begin at 0, so gems[1] is opal.'],
 ['beginner','debug-css','The title should be blue.','h1 {\n  colour: blue;\n}','The CSS property is color','h1 cannot be styled','blue is not a valid color','CSS uses the property name color, without a u.'],
 ['intermediate','debug-loop','This counter never reaches the exit.','for (let i = 0; i < 5; i--) {\n  console.log(i);\n}','Increase i instead of decreasing it','Loops cannot use numbers','console.log is invalid','Starting at 0 and decreasing keeps i below 5. i++ lets the loop finish.'],
 ['intermediate','debug-equal','The gate opens even without a key.','let hasKey = false;\nif (hasKey = true) {\n  openGate();\n}','= assigns true instead of comparing','false must be a string','if cannot use a variable','Use if (hasKey) or a comparison. A single = changes hasKey to true.'],
 ['intermediate','debug-return','The result is undefined.','const double = n => {\n  n * 2;\n};\nconsole.log(double(3));','The function needs return n * 2','Multiplication is not allowed','3 cannot be an input','A block-bodied arrow function needs return to provide a result.'],
 ['intermediate','debug-call','The greeting never appears.','const greet = () => console.log("Hi!");\ngreet;','Call it with greet()','Use a different message','Functions cannot log text','Writing greet refers to the function; parentheses call it.'],
 ['advanced','debug-bound','An extra undefined value appears.','const gems = [2, 4, 6];\nfor (let i = 0; i <= gems.length; i++) {\n  console.log(gems[i]);\n}','Use i < gems.length','Start at i = 1','Remove the increment','The last valid index is length minus 1. <= allows one extra iteration.'],
 ['advanced','debug-map','Every item becomes undefined.','const doubled = [1, 2].map(n => {\n  n * 2;\n});','Return n * 2 from the callback','map cannot use arrays','Use a string instead of 2','map builds a new array from callback return values. This callback returns nothing.'],
 ['advanced','debug-scope','The total cannot be found.','if (true) {\n  let total = 5;\n}\nconsole.log(total);','total is outside its block scope','Numbers cannot be logged','if requires an else','let is block-scoped. Declare total in the outer scope if it is needed there.'],
 ['advanced','debug-dom','The button cannot be found.','<!-- HTML: <button id="go">Go</button> -->\nconst button = document.querySelector("go");','Select the ID with "#go"','Use the selector "@go"','Buttons cannot have IDs','An ID selector begins with #. The selector go would look for a go element.']
];
export const debugChallenges = debugRows.map(([difficulty,id,scenario,code,correct,a,b,explanation])=>({id,difficulty,category:'debug',scenario,code,question:'What needs fixing?',options:[correct,a,b],answer:0,explanation}));
